export { default as AccountView } from "./Account";
// export { default as BrandView } from "./Brand";  
export { default as DashboardView } from "./Dashboard";  
export { default as LoginView } from "./Auth/Login";  
export { default as NotFoundView } from "./NotFound";  
export { default as ManualView } from "./Manual";  
// export { default as ProductView } from "./Product";  
export { default as ProfileView } from "./Profile";  
// export { default as SubCategoryView } from "./SubCategory";  
export { default as StageOneView } from "./reconcillations/StageOne";  
export { default as StageTwoView } from "./reconcillations/StageTwo";  
export { default as FinalStageView } from "./reconcillations/FinalStage";  